spring:
  application:
    name: E_Library
  config:
    import: external_config.yml
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: 
        format_sql: true
    show_sql: true
  mvc:
    cors:
      mapping:
        /book/getAllPaginated:
          allowed-origins: "http://localhost:8080"
          allowed-methods: "GET, POST, PUT, DELETE"
          allowed-headers: "*"
        /worker/updateNewsPost:
          allowed-origins: "http://localhost:3000"
          allowed-methods: "GET, POST, PUT, DELETE, OPTIONS"
          allowed-headers: "*"