spring:
  application:
    name: E_Library
  config:
    import: external_config.yml
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: 
        format_sql: true
    show_sql: true
  mvc:
    cors:
      mapping:
        /book/getAll:
          allowed-origins: "http://localhost:3000"
          allowed-methods: "GET, POST, PUT, DELETE"
          allowed-headers: "*"